FROM golang:1.20

WORKDIR /app

# Copy the go.mod, go.sum, and .env files into the container.
COPY go.mod go.sum .env ./

# Download the Go modules.
RUN go mod download

# Copy the rest of the source code into the container.
COPY . .

# Run the Go application.
CMD ["go", "run", "./..."]

# Expose port 8080 to the outside world.
EXPOSE 8080
